name: Build Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:

  Formate:
    runs-on: macos-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3

      - name: Install Swiftformat
        run: brew install swiftformat

      - name: Formate
        run: swiftformat --lint --swiftversion 5.5 .

  Build:
    runs-on: macos-latest
    timeout-minutes: 30
    needs: Formate

    steps:
      - uses: actions/checkout@v3

      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: CI Setup
        run: ./Scripts/ci_setup.sh 

      - name: Generation
        run: xcodegen generate

      - name: Build
        run: |
          xcodebuild clean build \
          -project BeRich.xcodeproj \
          -scheme BeRich \
          -configuration Debug \
          -sdk iphonesimulator \
          CODE_SIGNING_REQUIRED=NO
